### ISSUE TITLE
Suggestion for repo/packaging

### ISSUE THREAD

**Issue by kylecordes** [matyunya/smelte#1]
Here is a suggestion for how this project could reside in its repository and be packaged.

Convert this repo to a “mono repo” containing 4 projects.

* project containing all these components, published to NPM
* project containing the documentation, published to the web presence
* project containing a starter application showing correct rollup configuration to consume the components (with proper “CSS tree shaking” of Tailwind)
* example project showing all of the components in use

(it's possible that the third should reside in a separate repository, not part of a monorepo, to make it most clear how to use it as a starting point.)

**Comment by matyunya** [comment]
Thank you for suggestion!

Packaging is one of the biggest concerns for me at the moment. I think it would be easier to start by creating a Sapper template importing all the components from a different package with some dummy layout similar to https://smelte.matyunya.now.sh/.

The components repo then should contain documentation and some dev environment like storybook for all the components.

I'm not sure how to ship outside Sapper though.

**Comment by Kiho** [comment]
@kylecordes I like to find solution like you describe, but is there any project example in github we can follow? I found something for sapper https://github.com/nedkelly/sapper-monorepo but could find none for just svelte.

**Comment by matyunya** [comment]
Here's the Sapper template https://github.com/matyunya/smelte-template. I'll create svelte template eventually. The components, docs, and examples, as well as smelte site all will be in this repo. I'm not sure lerna is required in this case.

**Comment by Kiho** [comment]
IMO, lerna is needed for clear separation between components & application.

**Comment by kylecordes** [comment]
Here is another complication. There is a mechanism defined by which the Svelte compiler can see the Svelte source code for components brought in via node_modules (important for best developer experience and smallest output:

https://github.com/rollup/rollup-plugin-svelte#pkgsvelte

As far as I can tell, this mechanism assumes an NPM package exposes just a single Svelte component, not a set of components. So it seems that a project like this one will need to ship many separate parallel NPM packages, not just one, for efficient consumption downstream.

**Comment by kylecordes** [comment]
@matyunya ... Or to avoid limitation I described, a project like the template you have created can have ad hoc handling to reach inside a package and find all of the Svelte component source.

I think this is not a great long term solution, but nonetheless it is the best currently available until there is an "official" way for a single package to expose a set of components.

**Comment by matyunya** [comment]
It already does and it points to source code:
https://github.com/matyunya/smelte-template/blob/master/rollup.config.js#L100
I'm not sure we need to compile standalone components in case with Tailwind, unless we expose all of the components styles.

**Comment by Kiho** [comment]
Sapper might be a good platform for someone just work with node, but for me I prefer back-end code with strong type(C#) and RDBMS, so, I need to find out client side solution.

**Comment by matyunya** [comment]
Then let's build svelte template? It should not be much different from Sapper really, just a few tweaks in the rollup config?

**Comment by matyunya** [comment]
Also I am splitting out certain components into separate modules, but for now it's only those that don't depend on Tailwind:
https://github.com/matyunya/svelte-waypoint
https://github.com/matyunya/svelte-image

**Comment by Kiho** [comment]
I tried to build mono-repo here https://github.com/Kiho/smelte-monorepo
It's kind of working with some broken parts, specially List & Tabs
