### ISSUE TITLE
Discord invite link are expired/broken

### ISSUE THREAD

**Issue by dhonx** [matyunya/smelte#106]
Hi ... I want to join the `smelte` discord server, but it looks like the link has expired.

**Comment by SureDroid** [comment]
Found it. Here is the link to the discord server: https://discord.gg/Fdyqpt9

Warning, it seems to be fairly inactive at the moment.

**Comment by dhonx** [comment]
Thanks @SureDroid !

**Comment by benjamin-kirkbride** [comment]
New link: https://discord.gg/M9tQnNps
