### ISSUE TITLE
Unexpected PurgeCSS Behavior

### ISSUE THREAD

**Issue by SureDroid** [matyunya/smelte#115]
From my experimentation with smelte, I found some weird behavior. Here is a [demo repository](https://github.com/SureDroid/smelte-template/tree/purge-issue). Here, smelte is added to the server in rollup and tailwind is imported in server.js. 

It works normally during development, but when you build with production, purgecss seems to delete the bg-primary-500 class. However, whenever you add a second button and use a default tailwind color such as blue, it doesn't delete the bg-primary-500 class. 

This behavior is pretty unexpected and I'm not particularly sure why it's happening. My best guess would be that it has to do something with the css-extractor in util, but I'm not completely sure.

**Comment by mlandisbqs** [comment]
My team is also seeing something similar. It's also impacting the way some textfields are rendered. The issue goes away after disabling purge (purge:false).

**Comment by pwwang** [comment]
Same here. And I can confirm that adding another button with `color="blue"` keeps the `bg-primary-500` class.

**Comment by GiorgosK** [comment]
Seeing similar, styles are lost after `yarn build` on `yarn dev` things are working properly
If I put `purge: false` on rollup.config.js things work but no purging occurs

**Comment by cliveportman** [comment]
I know this is closed, but I'm finding background colours are being purged still.

**Comment by micha-lmxt** [comment]
I didn't go through all components to fix :Hover classes, If that is missing. Which component is affected?

**Comment by ChosenQuill** [comment]
@matyunya I don't think this issue should be closed, because it continues to remain as an issue. The PR explicitly mentioned that the fix provided is a workaround whitelist, not a legitimate resolution. As the whitelist might not work for all future components, people will continue to open issues. This thread should be where we can discuss potential ways to actually resolve the issue.

**Comment by micha-lmxt** [comment]
Please make sure that you use the latest version. It has only been published to npm two days ago.
