### ISSUE TITLE
Add more properties to Snackbar

### ISSUE THREAD

**Issue by Kiho** [matyunya/smelte#13]
Can we add position & type properties to Snackbar something similar as this?https://c0bra.github.io/svelma/components/snackbar

**Comment by matyunya** [comment]
Added color and position props, also exposed transition props and added class builder. Is it ok for you now?

**Comment by Kiho** [comment]
It's working good, sorry I forgot, but can you make that stackable?
Thanks.

**Comment by matyunya** [comment]
@Kiho what do you mean exactly?

**Comment by Kiho** [comment]
Show multiple instances Snackbars instead of hiding old instances.
https://user-images.githubusercontent.com/11908147/59467718-98183680-8ded-11e9-8ba4-ca2cb9460119.png

**Comment by matyunya** [comment]
You mean notification system like this?
https://svelte-notifications.netlify.com/

**Comment by Kiho** [comment]
Yes, that's it.

**Comment by matyunya** [comment]
Implemented simple notification system according to material spec.
