### ISSUE TITLE
Svelte 2.24.0 TextField issue with bind:value

### ISSUE THREAD

**Issue by mkelandis** [matyunya/smelte#146]
Per @bradak1 report on discord, we've upgraded svelte to 2.24.0 and have issues with TextField and 2-way binding.  I've modified the example code on a forked branch to demonstrate (text-fields.svelte):

![image](https://user-images.githubusercontent.com/2457369/88423594-003f9700-cdba-11ea-85e7-7038b56bfbdd.png)

- The initial value always restores itself
- When replacing the value it resets to intial value when focus changes
- When editing the value it jumps to the end of the string after a single character is inserted

Here is a demo:
![smelte-textfield](https://user-images.githubusercontent.com/2457369/88424012-ccb13c80-cdba-11ea-8630-ad079b508761.gif)

...I'm still grokking why this is happening and don't yet have a fix. Not 100% sure this is a smelte issue and not a svelte issue but I couldn't recreate it with vanilla svelte.

**Comment by matyunya** [comment]
This should be fixed in 1.0.15.
