### ISSUE TITLE
NavigationDrawer (part of documentation or code missing)

### ISSUE THREAD

**Issue by Florian-Schoenherr** [matyunya/smelte#154]
The documentation of the [NavigationDrawer](https://github.com/matyunya/smelte/blob/master/examples/navigation-drawers.txt) should be modified, some things are missing (and I don't know how it works, either):

- Is stores.js supposed to be bundled with smelte, or made by the user?
->Answer: it's just a js file with stores in it, I was really new to svelte when I used this
- Also, 'path' is not defined, so where is that supposed to be coming from?
->Answer: path is obtainable like this:
```
import { stores } from '@sapper/app';
const { preloading, page, session } = stores();
```
- How can I really use the Navigation Drawer? Please, if someone is really inside the codebase, try to update the docs.
I think the docs are the only big part lacking for people to take this into production.

**Comment by cliveportman** [comment]
Have a look how it's done in this sample template for a better idea: https://github.com/matyunya/smelte-sapper-template/blob/master/src/routes/_layout.svelte

**Comment by Florian-Schoenherr** [comment]
I totally agree with you there, I think I will retry this lib at some point. When I opened this issue, I was even more of a noob in svelte/sapper, so from a beginners perspective, I couldn't find out how to work with smelte. That's also the reason why I wrote "someone inside the codebase" should update the docs.
Closing this.
