### ISSUE TITLE
Npm package does not contain type declaration files

### ISSUE THREAD

**Issue by g5becks** [matyunya/smelte#166]
Hi. I just installed this package in a project using typescript and the version on npm doesn't contain the type declarations.

I noticed that there are indeed types for all of the components in the repo. Is there any specific reason they aren't provided on npm?

**Comment by mkelandis** [comment]
I just threw up a PR for this, not sure how to test without publishing the package.
https://github.com/matyunya/smelte/pull/175

**Comment by g5becks** [comment]
I'm not sure there is a way to test that without publishing. It should just work though. Only other option is to copy all the types and publish them to definitely typed.

**Comment by micha-lmxt** [comment]
Today I pulled the newest version of smelte from npm and the type declarations in the folder src are missing, while the type definitions in all subfolders are there. The missing file "src/index.d.ts" is causing the issue.

So currently importing component directly works (eg: import Sel from 'smelte/src/components/Select'), but the convenient way (import {Select as Sel} from 'smelte') does not.

**Comment by micha-lmxt** [comment]
Ok, just tested something. The direct component import does also not work, unless you install svelte-typed-component. I added a pull request to move the library to dependencies.

**Comment by mkelandis** [comment]
For us - the imports work but svelte-check complains with errors and breaks our build.

```sh
> svelte-check --output=machine

1601642482637 START "/Users/mlandis/repos/git/bqp/site"
1601642493118 ERROR "src/components/account/AccountFormDialog.svelte" 34:1 "JSX element class does not support attributes because it does not have a '$$prop_def' property."
1601642493119 ERROR "src/components/account/AccountFormDialog.svelte" 34:2 "Type definitions are missing for this Svelte Component. It needs a class definition with at least the property '$$prop_def' which should contain a map of input property definitions.\nExample:\nclass ComponentName { $$prop_def: { propertyName: string; } }\n\n'Dialog' cannot be used as a JSX component.\n  Its instance type 'Dialog' is not a valid JSX element.\n    Property '$$prop_def' is missing in type 'Dialog' but required in type 'ElementClass'."
1601642493119 ERROR "src/components/account/AccountFormDialog.svelte" 39:7 "JSX element class does not support attributes because it does not have a '$$prop_def' property."
1601642493119 ERROR "src/components/account/AccountFormDialog.svelte" 39:8 "Type definitions are missing for this Svelte Component. It needs a class definition with at least the property '$$prop_def' which should contain a map of input property definitions.\nExample:\nclass ComponentName { $$prop_def: { propertyName: string; } }\n\n'TextField' cannot be used as a JSX component.\n  Its instance type 'TextField' is not a valid JSX element.\n    Property '$$prop_def' is missing in type 'TextField' but required in type 'ElementClass'."
[...]
```

^-- ultimate goal is to make these go away.
