### ISSUE TITLE
[Sapper] "chunk.imports is not iterable" on fresh install

### ISSUE THREAD

**Issue by karlos1337** [matyunya/smelte#179]
Can't use smelte on a fresh sapper installation, throws `chunk.imports is not iterable`

```sh
npx degit "sveltejs/sapper-template#rollup" app
cd app
node scripts/setupTypeScript.js
npm i
npm i -S smelte
```
[rollup.config.js](https://gist.github.com/karlos1337/7f6a7b2e34253a08ef2d6b6e9c44d9a0)

```sh
npm run dev
```
![imagen](https://user-images.githubusercontent.com/1143362/95325526-9e170e00-08a1-11eb-8ec3-f757d5073249.png)

**Comment by colwilson** [comment]
same error although not typescript in my case.

**Comment by karlos1337** [comment]
Exporting only plugins and inject them as postcss sveltePreprocess option in both client and server seems works but increase a lot build time (~20s+), not an acceptable solution but maybe could help to find the way.

node_modules/smelte/rollup-plugin-smelte.js
```
// module.exports = (config = {}) =>
//   postcss({
//     plugins: plugins(config),
//     extract: path.resolve("./test/global.css")
//   });
module.exports = (config = {}) => plugins(config)
```

rollup.config.js
```
client: {
  svelte({
    preprocess: sveltePreprocess({ postcss: { plugins: smelte() } }),
[...]
server: {
  svelte({
    preprocess: sveltePreprocess({ postcss: { plugins: smelte() } }),
```

**Comment by micha-lmxt** [comment]
Perhaps [this link](https://codechips.me/sapper-with-postcss-and-tailwind/) is helpful?

What smelte/tailwind does is it creates a huge css file and purges it based on the used styles. I'm no expert on sapper, but I think it can have a global css file for the server and individual css files for each route. Probably it makes sense, to put the smelte/tailwind css to the server css file. 

I think this is done on the link as a extra process prior to bundling.

**Comment by micha-lmxt** [comment]
Seems to work! See [sapper-smelte-app](https://github.com/micha-lmxt/sapper-smelte-app)

**Comment by micha-lmxt** [comment]
Alternatively you can look [here (sapper-svelte-material-ui)](https://github.com/csaltos/sapper-svelte-material-ui). The build process is a bit cleaner. The purge process seems to be hard-coded, though.

**Comment by benmccann** [comment]
This was reported over in the Sapper repo: https://github.com/sveltejs/sapper/issues/1613#issuecomment-717339093. I think the issue is that Smelte is using an old version of Rollup. Can someone try upgrading Rollup and all its plugins to their latest versions?

**Comment by GitGangGuy** [comment]
Experiencing the same issue :/
