### ISSUE TITLE
smelte in Deno TypeScript projects?

### ISSUE THREAD

**Issue by shah** [matyunya/smelte#182]
I'm interested in using `smelte` in Deno-based TypeScript projects and was curious if anyone has done this already or has suggestions about why this might not be a good idea?

**Comment by awhitford** [comment]
What is the point?  The Svelte JavaScript is running in the browser.  Where would Deno fit?

**Comment by shah** [comment]
Good point @awhitford - I noticed `npm` was required so I assumed it was a server-side package which is why I inquired about Deno support. We do not use `npm` and are using Deno on the server-side but if `smelte` can be used purely on the client side with no server-side dependencies then you're right there's no point. I'll close this for now but please let me know if I've missed anything.
