### ISSUE TITLE
Snowpack Integration

### ISSUE THREAD

**Issue by 4350pChris** [matyunya/smelte#193]
Is there any way to integrate Smelte with [Snowpack](https://www.snowpack.dev/)?

I have tried adding the rollup plugin to snowpack under installOptions.rollup.plugins, but this leads to an error saying `Import "tailwindcss/base" could not be resolved.
If this import doesn't exist in the source file, add "install": ["tailwindcss/base"] to your Snowpack config file.` This error originates from including `@import "smelte/src/tailwind";` anywhere in my project, regardless of trying to import it in the `<style>` tag of a Svelte file or in its own `.css` file.
Any help would be much appreciated.

**Comment by PiotrBaczkowski** [comment]
It would be amazing, because of svelte kit is based on snowpack

**Comment by khanguyen88** [comment]
I managed to cobble Smelte with Snowpack: https://github.com/khanguyen88/smelte-typescript-snowpack

The process involved some copy/paste of Smelte's CSS. The project may have some issues since I'm relative new to Svelte/Snowpack ecosystem :)
