### ISSUE TITLE
http 502: service unavailable when reaching https://smelte.matyunya.now.sh/

### ISSUE THREAD

**Issue by opensas** [matyunya/smelte#2]
When visiting https://smelte.matyunya.now.sh/ I get:

```
The application is currently unavailable.

The application is not currently able to service the request.

503: SERVICE_UNAVAILABLE Code: V1_NO_SCALED_DEPLOYMENTS ID: gru1:v8gtw-1562732107609-fd5e079c3dfd

    If you are a visitor; contact the website owner or try again later.
    If you are the owner; check out the scaling docs or run `now scale --help`.
```

**Comment by matyunya** [comment]
@opensas Is it still down? It must be deployed to all regions, I wonder if I should convert it back to exported version.

**Comment by matyunya** [comment]
https://smelte.netlify.com/ I deploy to netlify too by the way. It's a tad slower but completely free.

**Comment by opensas** [comment]
> 
> 
> @opensas Is it still down? It must be deployed to all regions, I wonder if I should convert it back to exported version.

Yeap, still down here from buenos aires, argentina, netlify works ok

**Comment by matyunya** [comment]
deploying to netlify by default
