### ISSUE TITLE
TailwindCSS 2

### ISSUE THREAD

**Issue by awhitford** [matyunya/smelte#207]
What is the plan to support [Tailwind CSS 2](https://blog.tailwindcss.com/tailwindcss-v2)?
* https://tailwindcss.com/docs/upgrading-to-v2

For a _new_ project, it would be great to see the latest Tailwind CSS 2 being used to avoid a later migration effort.

**Comment by matyunya** [comment]
I'm sorry it took a while because of some dependencies stuck in PostCSS 7. Everything should work fine now.
