### ISSUE TITLE
Broken Ripple Effect

### ISSUE THREAD

**Issue by gotys** [matyunya/smelte#21]
Followed instructions to get started from the template:
`npx degit matyunya/smelte-sapper-template my-svelte-project`

Now every time I click on a link, the ripple effect breaks the CSS - examining Chrome Dev Tools, there is no class called "ripple-normal"

I think I need to run a command to recompile your tailwind.css but do not know how . Please help

**Comment by matyunya** [comment]
Thanks for the report!

This should be fixed now, please try to run it again.

**Comment by gotys** [comment]
Works ! Thank you very much
