### ISSUE TITLE
Chips display Broken on mobile

### ISSUE THREAD

**Issue by greaka** [matyunya/smelte#22]
Chips break on Click on mobile devices 

The width gets updated on click

Example after 2 clicks:

![Example after 2 clicks by greaka](https://i.imgur.com/mB3wsgW.jpg)

Tested on safari and brave on iOS 12.3

**Comment by matyunya** [comment]
Thank you for your report! Will fix over the weekend.

**Comment by matyunya** [comment]
I'm sorry it took me so long. Should be fixed in 0.1.9.
