### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by IJOY94** [matyunya/smelte#223]
Not sure if this is just me being stupid, but I cannot for the life of me, get CSS customization of the default Smelte components. 

Steps to reproduce:
1. Create new sveltejs/template
2. Run `npm install`
3. Run `npm install smelte`
4. Follow the instructions on the smeltejs website:
- Add `const smelte=require("smelte/rollup-plugin-smelte");` just below the existing `const production = !process.env.ROLLUP_WATCH;`
- Add everything contained by the Smelte plugin 
`  smelte({ 
    purge: production,
    output: "public/global.css", // it defaults to static/global.css which is probably what you expect in Sapper 
    postcss: [], // Your PostCSS plugins
    whitelist: [], // Array of classnames whitelisted from purging
    whitelistPatterns: [], // Same as above, but list of regexes
    tailwind: { 
      colors: { 
        primary: "#b027b0",
        secondary: "#009688",
        error: "#f44336",
        success: "#4caf50",
        alert: "#ff9800",
        blue: "#2196f3",
        dark: "#212121" 
      }, // Object of colors to generate a palette from, and then all the utility classes
      darkMode: true, 
    }, 
    // Any other props will be applied on top of default Smelte tailwind.config.js
  }),`
- Place this after svelte, and before css
5. Add the import line suggested so we can test if things are working `import "smelte/src/tailwind.css" ;`
6. Add a Button component
7. Since we assume that just those two things are needed, run `npm run dev`
8. Get error `Cannot find module 'rollup-plugin-postcss'`
9. Install rollup-plugin-postcss `npm install rollup-plugin-postcss`
10. Try step 7 again
11. Get error `Cannot find module 'autoprefixer'`
12. Install autoprefixer `npm install autoprefixer`
13. Try step 7 again
14. Get error `Error: [object Object] is not a PostCSS plugin` (What ???)

**Comment by jwsinner** [comment]
I'm experiencing the same issue. I tried asking in the discord channel but didn't any response yet. I'll be following along here.

**Comment by matyunya** [comment]
Please try again with 1.1.5. I put back missing runtime dependencies and was able to follow the installation steps using basic Svelte template. I actually used it to update: https://github.com/matyunya/smelte-template. Please try it and see if it works.

**Comment by jwsinner** [comment]
Thanks. Seems to be working now.
