### ISSUE TITLE
Is on:* working?

### ISSUE THREAD

**Issue by frederikhors** [matyunya/smelte#229]
I have seen [this code here](https://github.com/matyunya/smelte/blob/97e3bef0c51372a486ea8fc191ef1e4c05bce427/src/components/Button/Button.svelte#L163):

```svelte
  <button
    use:ripple
    class={classes}
    {...props}
    {type}
    {disabled}
    on:click={() => (value = !value)}
    on:click
    on:mouseover
    on:* <!-- this is what intrigued me -->
  >
    {#if icon}
      <Icon class={iClasses} {small}>{icon}</Icon>
    {/if}
    <slot />
  </button>
```

especially this is what intrigued me:

```svelte
on:*
```

I tried in my Svelte project and it doesn't work.

- Button.svelte:

```svelte
<button on:*>Click me please</button>
```

- App.svelte

```svelte
<Button on:click={()=>console.log("Clicked")} />
```

**Comment by matyunya** [comment]
`on:click` is passed up explicitly. I don't think Svelte can have a proper generic UI library without `on:*` but it takes very long time for features like this to be considered: https://github.com/sveltejs/svelte/pull/3349.

**Comment by frederikhors** [comment]
Ok, so it doesn't work, like I thought.

Thanks for your work!
