### ISSUE TITLE
Treeviews is not working.

### ISSUE THREAD

**Issue by SenerDemiral** [matyunya/smelte#28]

**Comment by kokizzu** [comment]
yeah, sometimes works, sometimes not '__') weird.. or maybe the delay before real expand soo long.

**Comment by matyunya** [comment]
Thanks, seems like this broke after last svelte upgrade. The framework is still changing a lot :(

**Comment by Kiho** [comment]
Treeview is working fine with svelte 3.10.0 or lower but problem with DataTable paging(https://github.com/matyunya/smelte/issues/26).
And it's reversed with 3.10.1 or higher.

**Comment by matyunya** [comment]
It seems like they're still updating `$$props` or spread operator behaviour. Will take closer look this week.

**Comment by matyunya** [comment]
Fixed in 0.1.4, thank you!
