### ISSUE TITLE
any plans to add a table component?

### ISSUE THREAD

**Issue by opensas** [matyunya/smelte#4]
A complete example, with sortable heading, striped tables, pagination and filtering would be awesome, btw

**Comment by matyunya** [comment]
Hey! I started one just a few days ago: https://smelte.netlify.com/components/data-tables. No pagination and filtering yet but sorting is there already.

**Comment by matyunya** [comment]
Added pagination.

**Comment by opensas** [comment]
They look nice, could you make the table responsive (add a horizontal scroll bar)

![imagen](https://user-images.githubusercontent.com/481687/61064815-da2a9d00-a3d8-11e9-98dd-948709d8a3ac.png)

**Comment by matyunya** [comment]
definitely, I'm not done with it yet :)

**Comment by matyunya** [comment]
basic component is there
