### ISSUE TITLE
Snackbar not working

### ISSUE THREAD

**Issue by BogdanDarius** [matyunya/smelte#40]
How to reproduce: 
1. Start a project with  ```html npx degit matyunya/smelte-template my-svelte-project```
2. Add a snackbar component
3. Gives an error ```ReferenceError: process is not defined```
![Screenshot from 2019-12-06 16-18-31](https://user-images.githubusercontent.com/25986436/70329743-be6eda00-1844-11ea-8e73-93975256c83f.png)

**Comment by matyunya** [comment]
Should be fixed now, please try again.
