### ISSUE TITLE
Icon size not applying

### ISSUE THREAD

**Issue by guillermin** [matyunya/smelte#45]
I'm trying to use <Icon xs>, but the Material Icons font css takes precendence over the text-xs class, so the icons are stuck at 24px.

**Comment by matyunya** [comment]
This should be fixed now, thank you!

**Comment by clockelliptic** [comment]
Gosh I hate to bring this back from the dead, but I'm running smelte latest (^1.0.15) and seeing this exact issue.

`<Button bind:value={$darkMode} icon="wb_sunny" iconClass="text-xs" small dark ></Button>`
