### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by bordunosp** [matyunya/smelte#51]
```
warning rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
warning rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
warning rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
warning rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.

```

**Comment by BogdanDarius** [comment]
Just upgrade those dependencies in `package.json`.

**Comment by bordunosp** [comment]
mb it should be upgrade in smelte-sapper-template?

**Comment by matyunya** [comment]
true, but it's pain upgrading templates' dependencies manually each time. I guess this is about time we switch to monorepo.

**Comment by BogdanDarius** [comment]
Well you can remove old dependencies using yarn:
`yarn remove  rollup-plugin-commonjs rollup-plugin-json rollup-plugin-node-resolve rollup-plugin-replace && yarn add @rollup/plugin-commonjs @rollup/plugin-json @rollup/plugin-node-resolve @rollup/plugin-replace`.
Make sure to update the `rollup.config.js` imports to match the new dependencies.
