### ISSUE TITLE
Additional component request - TreeView

### ISSUE THREAD

**Issue by Kiho** [matyunya/smelte#6]
Can we have TreeView component in the collection?

**Comment by matyunya** [comment]
Sure, seems like we could implement it as styled nested list

**Comment by Kiho** [comment]
I agree, but this looks good too 
https://github.com/arnedesmedt/vue-ads-table-tree
https://jsfiddle.net/arnedesmedt/7my8L42q
And using tailwind.

**Comment by matyunya** [comment]
Let's stop here for now.
