### ISSUE TITLE
Cannot find module 'smelte/src/stores.js'

### ISSUE THREAD

**Issue by mcanerizci** [matyunya/smelte#61]
First of all, thank you for your amazing work.

When I execute these commands,

1. npx degit matyunya/smelte-sapper-template smelte-test

2. cd smelte-test

3. npm install && npm run dev

I get an error like this. 

> Error: Cannot find module 'smelte/src/stores.js'
 

Here is the full output:

<pre>
<code>
[mcaner@mcaner smelte-test]$ npm install && npm run dev
npm WARN smelte-template@0.0.3 No repository field.
npm WARN smelte-template@0.0.3 No license field.

audited 3858 packages in 4.308s

23 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> smelte-template@0.0.3 dev /home/mcaner/Projects/frontend/smelte-test
> sapper dev

• client
'smelte/src/stores.js' is imported by src/routes/_layout.svelte, but could not be resolved – treating it as an external dependency
/home/mcaner/Projects/frontend/smelte-test/node_modules/smelte/src/components/TextField/TextField.svelte
TextField has unused export property 'labelClasses'. If it is for external reference only, please consider using `export const labelClasses`
40:   export let replace = "";
41: 
42:   export let labelClasses = "";
                 ^
43:   export let inputClasses = inputDefault;
44:   export let wrapperClasses = wrapperDefault;
/home/mcaner/Projects/frontend/smelte-test/node_modules/smelte/src/components/TextField/Label.svelte
Label has unused export property 'class'. If it is for external reference only, please consider using `export const class`
3: 
4:   let className = "";
5:   export {className as class};
             ^
6:   export let focused = false;
7:   export let error = false;
/home/mcaner/Projects/frontend/smelte-test/node_modules/smelte/src/components/TextField/Hint.svelte
Hint has unused export property 'color'. If it is for external reference only, please consider using `export const color`
 9:   export let error = false;
10:   export let hint = "";
11:   export let color = "primary";
                 ^
12: 
13:   export let add = "";
Circular dependency: src/node_modules/@sapper/app.mjs -> src/node_modules/@sapper/internal/App.svelte -> src/routes/_layout.svelte -> src/node_modules/@sapper/app.mjs
Circular dependency: node_modules/smelte/src/components/NavigationDrawer/index.js -> node_modules/smelte/src/components/NavigationDrawer/NavigationDrawer.svelte -> node_modules/smelte/src/index.js -> node_modules/smelte/src/components/NavigationDrawer/index.js
✔ service worker (453ms)
• server
'smelte/src/stores.js' is imported by src/routes/_layout.svelte, but could not be resolved – treating it as an external dependency
/home/mcaner/Projects/frontend/smelte-test/node_modules/smelte/src/components/TextField/TextField.svelte
TextField has unused export property 'labelClasses'. If it is for external reference only, please consider using `export const labelClasses`
40:   export let replace = "";
41: 
42:   export let labelClasses = "";
                 ^
43:   export let inputClasses = inputDefault;
44:   export let wrapperClasses = wrapperDefault;
/home/mcaner/Projects/frontend/smelte-test/node_modules/smelte/src/components/TextField/Label.svelte
Label has unused export property 'class'. If it is for external reference only, please consider using `export const class`
3: 
4:   let className = "";
5:   export {className as class};
             ^
6:   export let focused = false;
7:   export let error = false;
/home/mcaner/Projects/frontend/smelte-test/node_modules/smelte/src/components/TextField/Hint.svelte
Hint has unused export property 'color'. If it is for external reference only, please consider using `export const color`
 9:   export let error = false;
10:   export let hint = "";
11:   export let color = "primary";
                 ^
12: 
13:   export let add = "";
Circular dependency: src/routes/_layout.svelte -> src/node_modules/@sapper/app.mjs -> src/node_modules/@sapper/internal/App.svelte -> src/routes/_layout.svelte
Circular dependency: src/routes/_layout.svelte -> src/node_modules/@sapper/app.mjs -> src/node_modules/@sapper/internal/manifest-client.mjs -> src/routes/_layout.svelte
Circular dependency: node_modules/smelte/src/components/NavigationDrawer/index.js -> node_modules/smelte/src/components/NavigationDrawer/NavigationDrawer.svelte -> node_modules/smelte/src/index.js -> node_modules/smelte/src/components/NavigationDrawer/index.js
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
413: 
414:    // eslint-disable-next-line no-eval
415:   var deprecatedfn = eval('(function (' + args + ') {\n' +
                          ^
416:     '"use strict"\n' +
417:     'log.call(deprecate, message, site)\n' +
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'smelte/src/stores.js'
Require stack:
- /home/mcaner/Projects/frontend/smelte-test/__sapper__/dev/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/mcaner/Projects/frontend/smelte-test/__sapper__/dev/server/server.js:19:17)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mcaner/Projects/frontend/smelte-test/__sapper__/dev/server/server.js'
  ]
}
> Server crashed
</code>
</pre>

Thank you for your time.

**Comment by matyunya** [comment]
Thank you for reporting this! Should be fixed now after upgrading smelte.
