### ISSUE TITLE
bad instructions?

### ISSUE THREAD

**Issue by Rigel772** [matyunya/smelte#66]
After following the instructions to integrate it in existing project I tried with vanilla svelte...
And here is how date picker looks like:
https://snipboard.io/nCRzk8.jpg
Something is very wrong...
Way to reproduce:
- Clone svelte app
- follow instructions from readme.md
- insert code from https://smelte.netlify.com/components/date-pickers into App.js

The component neither looks ok nor works... 
`TypeError: ctx[0].toLocaleDateString is not a function`

**Comment by Rigel772** [comment]
...the look can be fixed by adding import to index.html:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

**Comment by matyunya** [comment]
Thank you for your report! Will add icons link to the readme.

Can you please push your repo somewhere so that I can take a look?

**Comment by Rigel772** [comment]
sorry, gave up smelt, going pure css ;)

**Comment by matyunya** [comment]
Good luck then :)
