### ISSUE TITLE
Can it be implemented in Angular?

### ISSUE THREAD

**Issue by taksumaki** [matyunya/smelte#75]
I have implementing TailwindCss with Angular but I have not found how to implement this in Angular or if possible.

**Comment by matyunya** [comment]
I'm working on something that would enable any framework to use Smelte by using plain js configuration object for all classes and using a small helper function to return a class string based on component state:
https://github.com/matyunya/smelte/blob/cb-v2/src/components/Button/config.js

```
const store = writable(config);
$: smelte = smelter($store, $$props);
...
<button
      class={smelte.button.class}
>
```
