### ISSUE TITLE
Select component doesn't respond to changes to error

### ISSUE THREAD

**Issue by polandj** [matyunya/smelte#78]
If you dynamically change the error for a Select component, it doesn't get reflected in the component.  It seems to only work if set at create time.  This works fine for TextField components.  For example:

```
<script>
let number, name
let numberError, nameError
const buy = () => {
    numberError = "Select a number"
    nameError = "Choose a name"
}
</script>

<Select bind:value={number} label="Number" error={numberError} />
<TextField bind:value={name} label="Name"  error={nameError} />
<Button on:click={buy}>Buy</Button>
```

The error shows up for the Name textfield, but nothing happens with the Number select.

**Comment by matyunya** [comment]
Thank you! This has been fixed in 1.0.10.
