### ISSUE TITLE
Tailwind CSS not bundled

### ISSUE THREAD

**Issue by grizar** [matyunya/smelte#79]
Hello,
Just getting an issue while starting a new project.
I followed the Smelte installation instructions and started my test project.
It looks like the tailwindcss is not bundled using rollup. Button using primary color are grey :-(

My bundle.css file is only few lines:

> @media(min-width: 640px){}
> .p-1\/2.svelte-ixci48{padding:0.125rem}
> .reverse.svelte-zzky5a{transform:rotate(180deg)}.tip.svelte-zzky5a{transform:rotate(90deg)}
> .drawer.svelte-12w8ugb{min-width:250px}aside.svelte-12w8ugb{height:calc(100vh - 4rem)}
> .inc.svelte-mguqwa{animation:svelte-mguqwa-increase 2s ease-in-out infinite}.dec.svelte-mguqwa{animation:svelte-mguqwa-decrease 2s 0.9s ease-in-out infinite}@keyframes svelte-mguqwa-increase{from{left:-5%;width:5%}to{left:130%;width:150%}}@keyframes svelte-mguqwa-decrease{from{left:-90%;width:90%}to{left:110%;width:10%}}
> .circular.svelte-1xkiyez{animation:svelte-1xkiyez-rotate 2s linear infinite;position:relative}.path.svelte-1xkiyez{stroke-dasharray:1, 200;stroke-dashoffset:0;stroke-linecap:round;animation:svelte-1xkiyez-dash 1.5s ease-in-out infinite}@keyframes svelte-1xkiyez-rotate{100%{transform:rotate(360deg)}}@keyframes svelte-1xkiyez-dash{0%{stroke-dasharray:1, 200;stroke-dashoffset:0}50%{stroke-dasharray:89, 200;stroke-dashoffset:-35}100%{stroke-dasharray:89, 200;stroke-dashoffset:-124}}
> th.svelte-1qy4u3g .asc.svelte-1qy4u3g{transform:rotate(180deg)}
> .label-top.svelte-81hn54{line-height:0.05}.label-transition.svelte-81hn54{transition:font-size 0.05s, line-height 0.1s}
> .tooltip.svelte-1n6auy7{left:50%;transform:translateX(-50%)}
> .line.svelte-xd9zs6{height:1px}
> .ripple.svelte-1o8z87d{position:absolute !important}
> .snackbar.svelte-1ym8qvd{min-width:344px}
> .wrapper.svelte-142y8oi{display:inline-block}
> 
> /*# sourceMappingURL=bundle.css.map */

The only way to make it work is to change the source mapping url line to 
> // sourceMappingURL=bundle.css.map

But this not not fully satisfactory.

The global.css includes a lot of tailwind stuff, even if do not import the tailwind.css using this line;

> import "smelte/src/tailwind.css";

I am using Chrome 80.
I suspect a minor issue but it make the whole thing not usable.

Grizar.

**Comment by watsy0007** [comment]
me 2

**Comment by grizar** [comment]
Really didn't understand what was happening. It seems to be working today, but didn't change anything!!!
I close the issue.
Well done for this nice library.
